name: p2p_signage
description: A new and clean implementation of the P2P signage system.
version: 1.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  json_annotation: ^4.0.0
  crypto: ^3.0.0
  ed25519_edwards: ^0.3.0
  cryptography: ^2.0.0
  intl: ^0.19.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.25.0
  build_runner: ^2.4.11
  json_serializable: ^6.8.0
